USE VEXLeaderboards;
-- Calculate All Team's Win Points
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "5454W") Where Team_Name = "5454W";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "98063A") Where Team_Name = "98063A";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "5454A") Where Team_Name = "5454A";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "51444D") Where Team_Name = "51444D";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "1853B") Where Team_Name = "1853B";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "8694N") Where Team_Name = "8694N";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "1430W") Where Team_Name = "1430W";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "9646C") Where Team_Name = "9646C";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "6754P") Where Team_Name = "6754P";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "2646F") Where Team_Name = "2646F";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "3015E") Where Team_Name = "3015E";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "6399G") Where Team_Name = "6399G";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "6517M") Where Team_Name = "6517M";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "9198A") Where Team_Name = "9198A";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "2364O") Where Team_Name = "2364O";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "3301T") Where Team_Name = "3301T";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "5440F") Where Team_Name = "5440F";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "2411N") Where Team_Name = "2411N";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "1229I") Where Team_Name = "1229I";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "5836N") Where Team_Name = "5836N";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "8845T") Where Team_Name = "8845T";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "3520U") Where Team_Name = "3520U";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "2925L") Where Team_Name = "2925L";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "6096T") Where Team_Name = "6096T";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "2294R") Where Team_Name = "2294R";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "4763N") Where Team_Name = "4763N";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "9159B") Where Team_Name = "9159B";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "8011K") Where Team_Name = "8011K";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "9665M") Where Team_Name = "9665M";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "1980H") Where Team_Name = "1980H";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "58664V") Where Team_Name = "58664V";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "21228Z") Where Team_Name = "21228Z";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "56384L") Where Team_Name = "56384L";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "62768T") Where Team_Name = "62768T";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "76174S") Where Team_Name = "76174S";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "45051M") Where Team_Name = "45051M";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "32013R") Where Team_Name = "32013R";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "43917R") Where Team_Name = "43917R";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "84506P") Where Team_Name = "84506P";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "10359D") Where Team_Name = "10359D";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "59550U") Where Team_Name = "59550U";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "87683E") Where Team_Name = "87683E";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "41980B") Where Team_Name = "41980B";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "68017H") Where Team_Name = "68017H";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "14059S") Where Team_Name = "14059S";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "28013D") Where Team_Name = "28013D";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "29006R") Where Team_Name = "29006R";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "66012U") Where Team_Name = "66012U";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "22993L") Where Team_Name = "22993L";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "27598H") Where Team_Name = "27598H";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "71310V") Where Team_Name = "71310V";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "68696S") Where Team_Name = "68696S";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "28489Q") Where Team_Name = "28489Q";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "82762H") Where Team_Name = "82762H";
Update Teams Set Win_Points = (Select Count(*) From Matches Where Winning_Team = "64216T") Where Team_Name = "64216T";

-- Calculate All Team's Strength Points
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "5454W") WHERE Team_Name = "5454W";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "98063A") WHERE Team_Name = "98063A";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "5454A") WHERE Team_Name = "5454A";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "51444D") WHERE Team_Name = "51444D";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "1853B") WHERE Team_Name = "1853B";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "8694N") WHERE Team_Name = "8694N";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "1430W") WHERE Team_Name = "1430W";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "9646C") WHERE Team_Name = "9646C";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "6754P") WHERE Team_Name = "6754P";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "2646F") WHERE Team_Name = "2646F";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "3015E") WHERE Team_Name = "3015E";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "6399G") WHERE Team_Name = "6399G";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "6517M") WHERE Team_Name = "6517M";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "9198A") WHERE Team_Name = "9198A";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "2364O") WHERE Team_Name = "2364O";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "3301T") WHERE Team_Name = "3301T";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "5440F") WHERE Team_Name = "5440F";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "2411N") WHERE Team_Name = "2411N";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "1229I") WHERE Team_Name = "1229I";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "5836N") WHERE Team_Name = "5836N";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "8845T") WHERE Team_Name = "8845T";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "3520U") WHERE Team_Name = "3520U";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "2925L") WHERE Team_Name = "2925L";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "6096T") WHERE Team_Name = "6096T";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "2294R") WHERE Team_Name = "2294R";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "4763N") WHERE Team_Name = "4763N";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "9159B") WHERE Team_Name = "9159B";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "8011K") WHERE Team_Name = "8011K";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "9665M") WHERE Team_Name = "9665M";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "1980H") WHERE Team_Name = "1980H";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "58664V") WHERE Team_Name = "58664V";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "21228Z") WHERE Team_Name = "21228Z";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "56384L") WHERE Team_Name = "56384L";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "62768T") WHERE Team_Name = "62768T";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "76174S") WHERE Team_Name = "76174S";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "45051M") WHERE Team_Name = "45051M";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "32013R") WHERE Team_Name = "32013R";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "43917R") WHERE Team_Name = "43917R";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "84506P") WHERE Team_Name = "84506P";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "10359D") WHERE Team_Name = "10359D";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "59550U") WHERE Team_Name = "59550U";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "87683E") WHERE Team_Name = "87683E";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "41980B") WHERE Team_Name = "41980B";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "68017H") WHERE Team_Name = "68017H";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "14059S") WHERE Team_Name = "14059S";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "28013D") WHERE Team_Name = "28013D";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "29006R") WHERE Team_Name = "29006R";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "66012U") WHERE Team_Name = "66012U";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "22993L") WHERE Team_Name = "22993L";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "27598H") WHERE Team_Name = "27598H";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "71310V") WHERE Team_Name = "71310V";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "68696S") WHERE Team_Name = "68696S";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "28489Q") WHERE Team_Name = "28489Q";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "82762H") WHERE Team_Name = "82762H";
Update Teams Set Strength_Points = (SELECT SUM(Losing_Score) FROM Matches WHERE Winning_Team = "64216T") WHERE Team_Name = "64216T";

-- Calculate All Team's Ranks
DROP PROCEDURE IF EXISTS UPDATERANKS;
DELIMITER ;;

CREATE PROCEDURE UPDATERANKS()
BEGIN
DECLARE X INT DEFAULT 0;
DECLARE Max INT DEFAULT 0;
SELECT COUNT(*) FROM Teams INTO Max;
SET X = 0;

while X < Max DO
UPDATE Teams SET Rank = (X+1) WHERE Team_Name = (Select Team_Name From (Select * From Teams) as top ORDER BY Win_Points DESC, Strength_Points DESC LIMIT 1 OFFSET X);
SET X = X + 1;
END WHILE;
END;
;;
DELIMITER ;
CALL UPDATERANKS();
